apiVersion: v1
kind: Namespace
metadata:
  name: vbnhdfghdfgdf-prod
  labels:
    environment-id: env_4885edd7-e378-4960-a421-41b3e7494fac
    project-id: project_4a5337b0-9eeb-4f9b-bc00-1e6e2a8a54d8
    project-name: vbnhdfghdfgdf
    environment-name: prod
    organization-id: org_9aad87d0-abbc-48f9-9038-002316f0475a
